### ISSUE TITLE
Automagic Dependencies PermissionError 

### ISSUE THREAD

**Issue by SmartManoj** [liftoff/pyminifier#105]
In pyx option
When Performing Automagic Dependencies occurs PermissionError: [Errno 13] Permission denied:  in python 3.6 win x64
If  p.py contains form . import anotherfille this occurs
pyminifier --pyz=l.pyz p.py 
Traceback (most recent call last):
  File "C:\Users\Smart\AppData\Local\Programs\Python\Python36-32\scripts\pyminifier-script.py", line 11, in <module>
    load_entry_point('pyminifier==2.1', 'console_scripts', 'pyminifier')()
  File "c:\users\smart\appdata\local\programs\python\python36-32\lib\site-packages\pyminifier\pyminifier.py", line 302, in main
    compression.zip_pack(pyz_file, options)
  File "c:\users\smart\appdata\local\programs\python\python36-32\lib\site-packages\pyminifier\compression.py", line 270, in zip_pack
    z.write(temp.name, module)
  File "c:\users\smart\appdata\local\programs\python\python36-32\lib\zipfile.py", line 1608, in write
    with open(filename, "rb") as src, self.open(zinfo, 'w') as dest:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Smart\\AppData\\Local\\Temp\\tmpjrbcnxbc'

**Comment by knekke** [comment]
Had the same problem.
Changing line 267 in compression.py to
`temp = tempfile.NamedTemporaryFile(mode='w', delete=False)`
solved it for me.
