### ISSUE TITLE
IndentationError: unindent does not match any outer indentation level

### ISSUE THREAD

**Issue by pentestor** [liftoff/pyminifier#125]
hey,
I want to obfuscate my script, but have an error in pyminifier

command:
pyminifier.exe -O script.py

error:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\Scripts\pyminifier-script.py", line 11, in <module>
    load_entry_point('pyminifier==2.1', 'console_scripts', 'pyminifier')()
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\pyminifier\pyminifier.py", line 398, in main
    source = minification.minify(tokens, options)
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\pyminifier\minification.py", line 512, in minify
    result = reduce_operators(result)
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\pyminifier\minification.py", line 187, in reduce_operators
    for tok in tokenize.generate_tokens(io_obj.readline):
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\tokenize.py", line 572, in _tokenize
    ("<tokenize>", lnum, pos, line))
  File "<tokenize>", line 395
    return hasher.digest()
    ^
IndentationError: unindent does not match any outer indentation level

**Comment by ghost** [comment]
Hello, this project is dead

**Comment by zengxiang68** [comment]
I have the same problem：`IndentationError: unindent does not match any outer indentation level`
