### ISSUE TITLE
TypeError: must be unicode, not str

### ISSUE THREAD

**Issue by mudgen** [liftoff/pyminifier#13]
I get the following error when using these options -O and -o:

Traceback (most recent call last):
  File "/usr/local/bin/pyminifier", line 9, in <module>
    load_entry_point('pyminifier==2.1', 'console_scripts', 'pyminifier')()
  File "build/bdist.linux-i686/egg/pyminifier/pyminifier.py", line 424, in main
TypeError: must be unicode, not str

**Comment by KenV99** [comment]
Still same problem running on Windows x64 from the command line as Admin

**Comment by KenV99** [comment]
I was able to overcome this by redirecting std output into a file and omitting the -o option and adding '> test.py' to the command line. But there were so many errors on running the obfuscated code that after repairing about ten, I've decided that either my code is too complex (which I am doubtful of) or the tool needs further work. Since this convo hasn't seen a reply in over 6 months I am assuming that it's an abandoned project.
