### ISSUE TITLE
Cant install pyminifier

### ISSUE THREAD

**Issue by ghost** [liftoff/pyminifier#136]
root@kali-linux:/tmp/pyminifier# python3 setup.py install
```
Traceback (most recent call last):
  File "/tmp/pyminifier/setup.py", line 2, in <module>
    import pyminifier
  File "/tmp/pyminifier/pyminifier/__init__.py", line 71, in <module>
    from collections import Iterable
ImportError: cannot import name 'Iterable' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
```

**Comment by ghost** [comment]
I cloned and ran python3 setup.py install

**Comment by ghost** [comment]
``` 
python3.9 setup.py install
error in pyminifier setup command: use_2to3 is invalid.
```
Python3.9 instead of Python3.10 gives this

**Comment by moimart1** [comment]
Not the best solution but this works for me with Python 3.10
```
pip install "setuptools<58.0.0"
```
