### ISSUE TITLE
Does not run on Kali Linux with Python 2.7.3 for me.

### ISSUE THREAD

**Issue by d4rkcat** [liftoff/pyminifier#22]
Hi, great tool, just found it today and was looking forward to seeing it in action.
Unfortunately I cannot get it to run on Linux kali 3.14-kali1-amd64 #1 SMP Debian 3.14.5-1kali1 (2014-06-07) x86_64 GNU/Linux

This os has python 2.7.3 installed as the default and also has python 3.2.3 installed.
These are the steps I went through:

git clone https://github.com/liftoff/pyminifier
cd pyminifier/pyminifier
./obfuscate.py

```
    Traceback (most recent call last):
      File "./obfuscate.py", line 13, in <module>
        from . import analyze
    ValueError: Attempted relative import in non-package
```

python3.2 obfuscate.py

```
    Traceback (most recent call last):
      File "obfuscate.py", line 13, in <module>
        from . import analyze
    ValueError: Attempted relative import in non-package
```

python pyminifier.py

```
    Traceback (most recent call last):
      File "pyminifier.py", line 71, in <module>
        from . import minification
    ValueError: Attempted relative import in non-package
```

So then I tried to install it to see if it would help.

cd .. && python setup.py install

```
    /usr/lib/python2.7/dist-packages/setuptools/command/install_scripts.py:3: UserWarning: Module pyminifier was already imported from /root/test/pyminifier/pyminifier/__init__.pyc, but /usr/local/lib/python2.7/dist-packages is being added to sys.path
      from pkg_resources import Distribution, PathMetadata, ensure_directory
    running install
    Checking .pth file support in /usr/local/lib/python2.7/dist-packages/
    /usr/bin/python -E -c pass
    TEST PASSED: /usr/local/lib/python2.7/dist-packages/ appears to support .pth files
    running bdist_egg
    running egg_info
    creating pyminifier.egg-info
    writing pyminifier.egg-info/PKG-INFO
    writing top-level names to pyminifier.egg-info/top_level.txt
    writing dependency_links to pyminifier.egg-info/dependency_links.txt
    writing entry points to pyminifier.egg-info/entry_points.txt
    writing manifest file 'pyminifier.egg-info/SOURCES.txt'
    file pyminifier.py (for module pyminifier) not found
    reading manifest file 'pyminifier.egg-info/SOURCES.txt'
    writing manifest file 'pyminifier.egg-info/SOURCES.txt'
    installing library code to build/bdist.linux-x86_64/egg
    running install_lib
    running build_py
    file pyminifier.py (for module pyminifier) not found
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/pyminifier
    copying pyminifier/obfuscate.py -> build/lib.linux-x86_64-2.7/pyminifier
    copying pyminifier/token_utils.py -> build/lib.linux-x86_64-2.7/pyminifier
    copying pyminifier/pyminifier.py -> build/lib.linux-x86_64-2.7/pyminifier
    copying pyminifier/compression.py -> build/lib.linux-x86_64-2.7/pyminifier
    copying pyminifier/__init__.py -> build/lib.linux-x86_64-2.7/pyminifier
    copying pyminifier/analyze.py -> build/lib.linux-x86_64-2.7/pyminifier
    copying pyminifier/minification.py -> build/lib.linux-x86_64-2.7/pyminifier
    file pyminifier.py (for module pyminifier) not found
    creating build/bdist.linux-x86_64
    creating build/bdist.linux-x86_64/egg
    creating build/bdist.linux-x86_64/egg/pyminifier
    copying build/lib.linux-x86_64-2.7/pyminifier/obfuscate.py -> build/bdist.linux-x86_64/egg/pyminifier
    copying build/lib.linux-x86_64-2.7/pyminifier/token_utils.py -> build/bdist.linux-x86_64/egg/pyminifier
    copying build/lib.linux-x86_64-2.7/pyminifier/pyminifier.py -> build/bdist.linux-x86_64/egg/pyminifier
    copying build/lib.linux-x86_64-2.7/pyminifier/compression.py -> build/bdist.linux-x86_64/egg/pyminifier
    copying build/lib.linux-x86_64-2.7/pyminifier/__init__.py -> build/bdist.linux-x86_64/egg/pyminifier
    copying build/lib.linux-x86_64-2.7/pyminifier/analyze.py -> build/bdist.linux-x86_64/egg/pyminifier
    copying build/lib.linux-x86_64-2.7/pyminifier/minification.py -> build/bdist.linux-x86_64/egg/pyminifier
    byte-compiling build/bdist.linux-x86_64/egg/pyminifier/obfuscate.py to obfuscate.pyc
    byte-compiling build/bdist.linux-x86_64/egg/pyminifier/token_utils.py to token_utils.pyc
    byte-compiling build/bdist.linux-x86_64/egg/pyminifier/pyminifier.py to pyminifier.pyc
    byte-compiling build/bdist.linux-x86_64/egg/pyminifier/compression.py to compression.pyc
    byte-compiling build/bdist.linux-x86_64/egg/pyminifier/__init__.py to __init__.pyc
    byte-compiling build/bdist.linux-x86_64/egg/pyminifier/analyze.py to analyze.pyc
    byte-compiling build/bdist.linux-x86_64/egg/pyminifier/minification.py to minification.pyc
    writing byte-compilation script '/tmp/tmpXwKM6s.py'
    /usr/bin/python -O /tmp/tmpXwKM6s.py
    removing /tmp/tmpXwKM6s.py
    creating build/bdist.linux-x86_64/egg/EGG-INFO
    copying pyminifier.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
    copying pyminifier.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
    copying pyminifier.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
    copying pyminifier.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
    copying pyminifier.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
    zip_safe flag not set; analyzing archive contents...
    creating dist
    creating 'dist/pyminifier-2.1-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
    removing 'build/bdist.linux-x86_64/egg' (and everything under it)
    Processing pyminifier-2.1-py2.7.egg
    creating /usr/local/lib/python2.7/dist-packages/pyminifier-2.1-py2.7.egg
    Extracting pyminifier-2.1-py2.7.egg to /usr/local/lib/python2.7/dist-packages
    Adding pyminifier 2.1 to easy-install.pth file
    Installing pyminifier script to /usr/local/bin

    Installed /usr/local/lib/python2.7/dist-packages/pyminifier-2.1-py2.7.egg
    Processing dependencies for pyminifier==2.1
    Finished processing dependencies for pyminifier==2.1
```

pyminifier -O ascript.py

```
    Traceback (most recent call last):
      File "/usr/local/bin/pyminifier", line 9, in <module>
        load_entry_point('pyminifier==2.1', 'console_scripts', 'pyminifier')()
      File "/usr/local/lib/python2.7/dist-packages/pyminifier-2.1-py2.7.egg/pyminifier/pyminifier.py", line 398, in main
        source = minification.minify(tokens, options)
      File "/usr/local/lib/python2.7/dist-packages/pyminifier-2.1-py2.7.egg/pyminifier/minification.py", line 523, in minify
        result = reduce_operators(result)
      File "/usr/local/lib/python2.7/dist-packages/pyminifier-2.1-py2.7.egg/pyminifier/minification.py", line 186, in reduce_operators
        for tok in tokenize.generate_tokens(io_obj.readline):
      File "/usr/lib/python2.7/tokenize.py", line 351, in generate_tokens
        ("<tokenize>", lnum, pos, line))
      File "<tokenize>", line 12
        try:
        ^
    IndentationError: unindent does not match any outer indentation level
```

I tried to change all of the
        from . import analyze
to
        import analyze

But it had no effect. I gave up at this point. Please any pointers would be appreciated, I will try this on a different linux OS soon.

Many Thanks
   d4rkcat

**Comment by jstream** [comment]
I am having the same issue on gentoo, and it happens regardless of whether I use python2.7 or python3.3

In addition to the above errors, when I try to setup.py --build, I get:
```
$ python3 setup.py build 
running build
running build_py
file pyminifier.py (for module pyminifier) not found
creating build
creating build/lib
creating build/lib/pyminifier
copying pyminifier/minification.py -> build/lib/pyminifier
copying pyminifier/pyminifier.py -> build/lib/pyminifier
copying pyminifier/analyze.py -> build/lib/pyminifier
copying pyminifier/__init__.py -> build/lib/pyminifier
copying pyminifier/obfuscate.py -> build/lib/pyminifier
copying pyminifier/token_utils.py -> build/lib/pyminifier
copying pyminifier/compression.py -> build/lib/pyminifier
Skipping implicit fixer: buffer
Skipping implicit fixer: idioms
Skipping implicit fixer: set_literal
Skipping implicit fixer: ws_comma
file pyminifier.py (for module pyminifier) not found
```

It's odd because the file is clearly present in both the build and pyminifier directories. Please help

**Comment by liftoff** [comment]
Well, the issue pointed out by @d4rkcat is different from @jstream .  That is a problem with the Python 2.7 installation:  The tokenize.py module is included with Python (standard lib) and it appears that that file is corrupted in Kali Linux (or at least the copy that @d4rkcat has).  Or it could be that pyminifier is having difficulty with `ascript.py` (whatever that is).

@d4rkcat Can you paste a few lines above and below that "try:" line inside `ascript.py` so I can see if it's a bug in pyminifier?

@jstream I think your issue might have to do with the version of setuptools or distutils that you have installed.  What version have you got?  It obviously doesn't like something in the setup.py.
