### ISSUE TITLE
pyminifier false : replace in obfuscate

### ISSUE THREAD

**Issue by cbogithub** [liftoff/pyminifier#26]
i try obfuscate  example on pyminifier github home page:

#!/usr/bin/python
x=ImportError
I=False
J=object
try:
 import demiurgic
except x:
 print("Warning: You're not demiurgic. Actually, I think that's normal.")
try:
 import mystificate
except x:
 print("Warning: Dark voodoo may be unreliable.")
N=I
class y(J):
 def __init__(self,*args,**kwargs):
  pass
 def R(self,dactyl):
  j=demiurgic.palpitation(dactyl)
  l=mystificate.dark_voodoo(j)
  return l
 def u(self,whatever):
  print(whatever)
if __name__=="__main__":
 print("Forming...")
 f=y("epicaricacy","perseverate")
 f.test("Codswallop")
# Created by pyminifier (https://github.com/liftoff/pyminifier)
=========================
Warning: You're not demiurgic. Actually, I think that's normal.
Warning: Dark voodoo may be unreliable.
Forming...
Traceback (most recent call last):
  File "bbbb.py", line 26, in <module>
    f.test("Codswallop")
AttributeError: 'y' object has no attribute 'test'

==============================

it lost  f.test("Codswallop") now is  f.u("Codswallop")

**Comment by cbogithub** [comment]
============= test1.py
```python
#!/usr/bin/env python
"""
tumult.py - Because everyone needs a little chaos every now and again.
"""

try:
    import demiurgic
except ImportError:
    print("Warning: You're not demiurgic. Actually, I think that's normal.")
try:
    import mystificate
except ImportError:
    print("Warning: Dark voodoo may be unreliable.")

# Globals
ATLAS = False # Nothing holds up the world by default

class Foo(object):
    """
    The Foo class is an abstract flabbergaster that when instantiated
    represents a discrete dextrogyratory inversion of a cattywompus
    octothorp.
    """
    def __init__(self, *args, **kwargs):
        """
        The initialization vector whereby the ineffably obstreperous
        becomes paramount.
        """
        # TODO.  BTW: What happens if we remove that docstring? :)

    def demiurgic_mystificator(self, dactyl):
        """
        A vainglorious implementation of bedizenment.
        """
        inception = demiurgic.palpitation(dactyl) # Note the imported call
        demarcation = mystificate.dark_voodoo(inception)
        return demarcation

    def test(self, whatever):
        """
        This test method tests the test by testing your patience.
        """
        print(whatever)

if __name__ == "__main__":
    print("Forming...")
    f = Foo("epicaricacy", "perseverate")
    f.test("Codswallop")
```
=============================

scrpit after obfuscated 
=========================testob.py

```python
#!/usr/bin/env python
n=ImportError
M=False
p=object
try:
 import demiurgic
except n:
 print("Warning: You're not demiurgic. Actually, I think that's normal.")
try:
 import mystificate
except n:
 print("Warning: Dark voodoo may be unreliable.")
E=M
class Y(p):
 def __init__(self,*args,**kwargs):
  pass
 def i(self,dactyl):
  v=demiurgic.palpitation(dactyl)
  G=mystificate.dark_voodoo(v)
  return G
 def Q(self,whatever):
  print(whatever)
if __name__=="__main__":
 print("Forming...")
 f=Y("epicaricacy","perseverate")
 f.test("Codswallop")
# Created by pyminifier (https://github.com/liftoff/pyminifier)
```
======================

and run : 

```
Warning: You're not demiurgic. Actually, I think that's normal.
Warning: Dark voodoo may be unreliable.
Forming...
Traceback (most recent call last):
  File "test1ob.py", line 26, in <module>
    f.test("Codswallop")
AttributeError: 'Y' object has no attribute 'test'
```

pyminifier still false  in raplace func

it true is:
```
 f.Q("Codswallop")
```
