### ISSUE TITLE
IndentationError: unindent does not match any outer indentation level

### ISSUE THREAD

**Issue by tracs1** [liftoff/pyminifier#40]
Traceback (most recent call last):
  File "D:\IDE\Python27\Scripts\pyminifier-script.py", line 9, in <module>
    load_entry_point('pyminifier==2.2', 'console_scripts', 'pyminifier')()
  File "build\bdist.win32\egg\pyminifier\__main__.py", line 170, in main
  File "build\bdist.win32\egg\pyminifier\__init__.py", line 284, in pyminify

  File "build\bdist.win32\egg\pyminifier\minification.py", line 414, in minify
  File "build\bdist.win32\egg\pyminifier\minification.py", line 266, in join_mul
tiline_pairs
  File "D:\IDE\Python27\lib\tokenize.py", line 358, in generate_tokens
    ("<tokenize>", lnum, pos, line))
  File "<tokenize>", line 27
    request_counter+=1
    ^
IndentationError: unindent does not match any outer indentation level

**Comment by cbogithub** [comment]
try replace "tab" with "    "  and try again....

**Comment by marcosps** [comment]
So, --use-tabs is broken now, as it mixes space/tabs within a method of python.

**Comment by darealshinji** [comment]
I get a similar error when I try to minify [animecheck.py](https://github.com/OmegaPhil/animecheck):

```
$ pyminifier animecheck.py 
Traceback (most recent call last):
  File "/usr/bin/pyminifier", line 9, in <module>
    load_entry_point('pyminifier==2.2', 'console_scripts', 'pyminifier')()
  File "/usr/lib/python2.7/dist-packages/pyminifier/__main__.py", line 171, in main
    pyminify(options, files)
  File "/usr/lib/python2.7/dist-packages/pyminifier/__init__.py", line 284, in pyminify
    source = minification.minify(tokens, options)
  File "/usr/lib/python2.7/dist-packages/pyminifier/minification.py", line 418, in minify
    result = dedent(result, use_tabs=options.tabs)
  File "/usr/lib/python2.7/dist-packages/pyminifier/minification.py", line 307, in dedent
    for i, tok in enumerate(tokenize.generate_tokens(io_obj.readline)):
  File "/usr/lib/python2.7/tokenize.py", line 357, in generate_tokens
    ("<tokenize>", lnum, pos, line))
  File "<tokenize>", line 372
    except Exception as e:
    ^
IndentationError: unindent does not match any outer indentation level
```
